apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ycsb-benchmark-manual-testing
  labels:
    app: ycsb-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ycsb
  template:
    metadata:
      labels:
        app: ycsb
    spec:
      hostNetwork: true
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - ycsb-runner
          topologyKey: topology.kubernetes.io/zone```
      serviceAccountName: ycsb-service-account
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app: ycsb
      nodeSelector:
        beta.kubernetes.io/instance-type: Standard_F8s_v2
      containers:
      - name: ycsb
        image: quay.io/breniserbrian/ycsb:latest
        command: ["/bin/bash", "-c"] 
        #run as root user to install packages
        securityContext:
          privileged: false
        args:
        - |
          host_index=$(echo $POD_NAME | grep -o '[0-9]\+')
          cd ycsb-foundationdb-binding-0.18.0-SNAPSHOT
          now=$(date +"%Y_%m_%d_%H_%M_%S")
          log_file="ycsb_host_${host_index}__$now.log"
          workloada='workloads/workloada'
          workloadb='workloads/workloadb'
          update_proportion=0.0
          read_proportion=1.0
          num_keys=200000000
          value_size_bytes=2000
          batch_size=200
          num_clients=60
          field_count=10
          field_length=100
          threads_per_process=32
          max_execution_time_seconds=200000
          keys_per_host=$((num_keys / num_clients))
          process_per_host=8
          keys_per_process=$((keys_per_host / process_per_host))
          operation_count=$((keys_per_host / batch_size))
          start_key_offset=0
          start_key_per_host=$((host_index*keys_per_host+start_key_offset))
          while true; do
            echo "Waiting for cluster file to be created"
            if [ -f $FDB_CLUSTER_FILE ]; then
              break
            fi
            sleep 5
          done
          ycsb_load_cmd="./bin/ycsb.sh load foundationdb -s \
            -P $workloada \
            -p foundationdb.apiversion=620 \
            -p foundationdb.clusterfile=$FDB_CLUSTER_FILE \
            -p recordcount=$num_keys \
            -p insertstart=$start_key_per_host \
            -p insertcount=$keys_per_host \
            -p operationcount=$operation_count \
            -p db.batchsize=$batch_size \
            -p maxexecutiontime=$max_execution_time_seconds \
            -p fieldcount=$field_count \
            -p fieldlength=$field_length \
            -p readproportion=$read_proportion \
            -p updateproportion=$update_proportion \
            -p requestdistribution=uniform \
            -p threadcount=$threads_per_process"
          ycsb_run_cmd="./bin/ycsb.sh run foundationdb -s \
            -P $workloadb \
            -p foundationdb.apiversion=620 \
            -p foundationdb.clusterfile=$FDB_CLUSTER_FILE \
            -p recordcount=$num_keys \
            -p insertstart=$start_key_per_host \
            -p insertcount=$keys_per_host \
            -p operationcount=$operation_count \
            -p foundationdb.batchsize=$batch_size \
            -p maxexecutiontime=$max_execution_time_seconds \
            -p fieldcount=$field_count \
            -p fieldlength=$field_length \
            -p readproportion=$read_proportion \
            -p updateproportion=$update_proportion \
            -p requestdistribution=uniform \
            -p threadcount=$threads_per_process"
          while true; do
            echo "Whatever... host $POD_NAME"
            sleep 100
          done
        env:
          - name: FDB_CLUSTER_FILE
            value: /mnt/config-volume/cluster-file
          - name: FDB_TLS_CERTIFICATE_FILE
            value: /var/fdb-certs/cert.pem
          - name: FDB_TLS_KEY_FILE
            value: /var/fdb-certs/key.pem
          - name: FDB_TLS_CA_FILE
            value: /var/fdb-ca-certs/cert.pem
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
          - name: fdb-certs
            mountPath: /var/fdb-certs
          - name: fdb-ca-certs
            mountPath: /var/fdb-ca-certs
          - name: config-volume
            mountPath: /mnt/config-volume
      volumes:
        - name: config-volume
          configMap:
            name: fdb-cluster-1-config
        - name: fdb-certs
          secret:
            secretName: fdb-certs
        - name: fdb-ca-certs
          secret:
            secretName: fdb-ca-certs
