apiVersion: apps.foundationdb.org/v1beta2
kind: FoundationDBCluster
metadata:
  name: {{name}}
  namespace: {{namespace}}
spec:
  storageServersPerPod: {{storageServersPerPod}}
  automationOptions:
    replacements:
      enabled: true
  faultDomain:
    key: foundationdb.org/none
  labels:
    podlabel: fdblabel
    filterOnOwnerReference: false
    matchLabels:
      foundationdb.org/fdb-cluster-name: {{name}}
    processClassLabels:
    - foundationdb.org/fdb-process-class
    processGroupIDLabels:
    - foundationdb.org/fdb-process-group-id
  minimumUptimeSecondsForBounce: 60
  processCounts:
    cluster_controller: {{cluster_controller}}
    storage: {{storage}}
    log: {{log}}
    stateless: {{stateless}}
  processes:
    general:
      podTemplate:
        metadata:
            annotations:
              #k8s.v1.cni.cncf.io/networks: bridge-main
              #v1.multus-cni.io/default-network: default/bridge-main
        spec:
          hostNetwork: true
          topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                foundationdb.org/fdb-cluster-name: fdb-cluster
          containers:
          - name: foundationdb
            resources:
              requests:
                cpu: 7000m
                memory: 31Gi
            securityContext:
              runAsUser: 0
          - name: foundationdb-kubernetes-sidecar
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 100m
                memory: 128Mi
            securityContext:
              runAsUser: 0
          initContainers:
          - name: foundationdb-kubernetes-init
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 100m
                memory: 128Mi
            securityContext:
              runAsUser: 0
      customParameters:
      - knob_disable_posix_kernel_aio=1
      volumeClaimTemplate:
        spec:
          storageClassName: managed-premium
          resources:
            requests:
              storage: {{volume_claim_storage}}
  routing:
    headlessService: {{headlessService}}
    publicIPSource: {{publicIPSource}}
  sidecarContainer:
    enableLivenessProbe: true
    enableReadinessProbe: true
  useExplicitListenAddress: true
  version: 7.1.26
