apiVersion: apps/v1
kind: Deployment
metadata:
  name: ycsb-deployment
spec:
  replicas: {{replicas}}
  selector:
    matchLabels:
      app: ycsb
  template:
    metadata:
      labels:
        app: ycsb
    spec:
      containers:
      - name: ycsb
        image: docker.io/ubuntu:latest
        command: ["/bin/bash", "-c"]
        volumeMounts:
          - name: config-volume
            mountPath: /mnt/config-volume
        args:
        - |
          apt-get update
          apt-get install -y wget openjdk-11-jdk tar python2
          wget https://github.com/brianfrankcooper/YCSB/releases/download/0.17.0/ycsb-0.17.0.tar.gz
          whoami
          ls -la
          echo ""
          sleep 5
          tar -xf ycsb-0.17.0.tar.gz
          cd ycsb-0.17.0
          while true; do
            echo "YCSB container is running"
            sleep 10
          done
      volumes:
        - name: config-volume
          configMap:
            name: fdb-cluster-config
