apiVersion: apps/v1
kind: Deployment
metadata:
  name: ycsb-deployment
spec:
  replicas: {{replicas}}
  selector:
    matchLabels:
      app: ycsb
  template:
    metadata:
      labels:
        app: ycsb
    spec:
      containers:
      - name: ycsb
        image: registry.redhat.io/ubi8/openjdk-11:latest
        command: ["/bin/bash", "-c"] 
        #run as root user to install packages
        securityContext:
          privileged: true  
        args:
        - |
          microdnf install -y git-core wget tar python2 
          microdnf clean all 
          ln -sf /usr/bin/python2.7 /usr/bin/python
          wget  https://github.com/adobe/newsql-benchmark/raw/main/ansible/roles/loadgen_ycsb_install/files/ycsb-foundationdb-binding-0.18.0-SNAPSHOT.tar.gz 
          tar -xvf ycsb-foundationdb-binding-0.18.0-SNAPSHOT.tar.gz
          rpm -i https://github.com/apple/foundationdb/releases/download/7.1.31/foundationdb-clients-7.1.31-1.el7.x86_64.rpm
          while true; do
            echo "YCSB container is running"
            sleep 20
          done

        env:
          - name: FDB_CLUSTER_FILE
            value: /mnt/config-volume/cluster-file
        volumeMounts:
          - name: config-volume
            mountPath: /mnt/config-volume  
      volumes:
        - name: config-volume
          configMap:
            name: test-cluster-config